<#
    .SYNOPSIS
        Generates the repository Codecov components configuration from a JSON map.
    .DESCRIPTION
        Produces .codecov.yml from DevOps/Quality/codecov-components-map.json.
        When -Validate is provided, compares generated content to the checked-in
        file and fails if drift is detected.
#>
[CmdletBinding()]
param(
    [string]$MapPath,
    [string]$OutputPath,
    [switch]$Validate
)

$repoRoot = Resolve-Path -Path (Join-Path -Path $PSScriptRoot -ChildPath '..\..')

if (-not $MapPath) {
    $MapPath = Join-Path -Path $PSScriptRoot -ChildPath 'codecov-components-map.json'
}
if (-not $OutputPath) {
    $OutputPath = Join-Path -Path $repoRoot -ChildPath '.codecov.yml'
}

if (-not (Test-Path -Path $MapPath)) {
    throw "Codecov component map file not found: $MapPath"
}

$map = Get-Content -Path $MapPath -Raw | ConvertFrom-Json
if ($null -eq $map.components -or $map.components.Count -eq 0) {
    throw 'Codecov component map does not contain any components.'
}

$generatedLines = @(
    '# This file is generated by DevOps/Quality/Generate-CodecovComponents.ps1',
    '# Source of truth: DevOps/Quality/codecov-components-map.json',
    'component_management:',
    '  individual_components:'
)

foreach ($component in $map.components) {
    if ([string]::IsNullOrWhiteSpace($component.id)) {
        throw 'A component id is missing in the map file.'
    }
    if ([string]::IsNullOrWhiteSpace($component.name)) {
        throw "Component '$($component.id)' is missing a name in the map file."
    }
    if ($null -eq $component.paths -or $component.paths.Count -eq 0) {
        throw "Component '$($component.id)' does not define any paths in the map file."
    }

    $generatedLines += "    - component_id: $($component.id)"
    $generatedLines += "      name: $($component.name)"
    $generatedLines += '      paths:'

    foreach ($pathPattern in $component.paths) {
        if ([string]::IsNullOrWhiteSpace($pathPattern)) {
            continue
        }
        $generatedLines += "        - $pathPattern"
    }
}

$generatedContent = ($generatedLines -join "`n") + "`n"

function Normalize-TextForComparison {
    param(
        [string]$Text
    )

    if ($null -eq $Text) {
        return ''
    }

    $normalized = $Text -replace "`r`n", "`n"
    if ($normalized.Length -gt 0 -and $normalized[0] -eq [char]0xFEFF) {
        $normalized = $normalized.Substring(1)
    }

    return $normalized.TrimEnd("`n")
}

if ($Validate) {
    if (-not (Test-Path -Path $OutputPath)) {
        throw "Codecov config file is missing: $OutputPath"
    }

    $existingContent = Get-Content -Path $OutputPath -Raw
    if ((Normalize-TextForComparison -Text $existingContent) -ne (Normalize-TextForComparison -Text $generatedContent)) {
        throw 'Codecov component config drift detected. Run: pwsh -File .\DevOps\Quality\Generate-CodecovComponents.ps1'
    }

    Write-Host 'Codecov component config validation passed.' -ForegroundColor Green
    return
}

Set-Content -Path $OutputPath -Value $generatedContent -Encoding utf8
Write-Host "Generated Codecov component config at: $OutputPath" -ForegroundColor Green
